@startuml

title Sequence Diagram with Add BookCopy function

autonumber

participant "BookControllerImpl" as bc
participant "BookServiceIml" as bs
participant "DataAccessFacade" as da

[o-> bc++: addNewBookCopy()
note over bc: validate input
bc -> bs++: searchBookByIsbn()
return book

note over bc: Check existing book
bc -> bs++: saveNewBookCopy()
bs -> da++: updateBook()
return book

return book

return book

@enduml