@startuml

title Sequence Diagram with Checkout function

autonumber

participant "UserController" as uc
participant "BookService" as bs
participant "LibraryMember" as lm
participant "CheckoutRecord" as cr
participant "DataAccess" as da

[o-> uc++: Checkout Book

note over uc: validate input

uc -> bs++: getAvailableBookCopy()
return BookCopy

uc -> lm++: Get Library Member
return libraryMember

uc -> cr++: Create new Checkout Record
deactivate

uc -> da++: Update BookCopy Availability
deactivate

uc -> da++: Save New Checkout Record
deactivate

@enduml