@startuml

title Sequence Diagram with Login function

autonumber

participant "UserController" as uc
participant "UserService" as us
participant "DataAccess" as da

[o-> uc++: Request Login
uc -> us++: Validate input
deactivate

uc -> da++: readUserMap()
da --> uc--: return Map

uc -> us++: Authentication
deactivate

uc -> us++: Authorization
deactivate

@enduml