@startuml

title Sequence Diagram with Login function

autonumber

participant "UserControllerImpl" as uc
participant "UserServiceImpl" as us
participant "DataAccessFacade" as da

[o-> uc++: Request Login
uc -> us++: Validate input
deactivate

uc -> da++: readUserMap()
da --> uc--: return Map

uc -> us++: Authentication
deactivate

uc -> us++: Authorization
deactivate

@enduml