@startuml

title Sequence Diagram with Login function

autonumber 1 1

actor User
participant "LoginWindow" as lw
participant "UserController" as uc
participant "DataAccess" as da
participant "Database" as db

User o-> lw: Request Login
lw -> uc: login(userName, password)
note over uc: validate input
uc -> da: Authorization
da -> db: Read user data
db --> uc: return user data
lw -> lw: navigate to app

@enduml